name: Semver Tag Action
description: Analyzes the latest Git tag and calculates the next version by applying a semantic version bump.
author: Acme Software LLC

branding:
  icon: moon
  color: red

inputs:
  token:
    description:
      The GitHub token to use for authentication. This token must have
      permission to read the repository's tags.
    required: true

  level:
    description:
      The level of the semantic versioning bump to apply. Options are major,
      minor, patch, premajor, preminor, prepatch, prerelease, or release.
    required: false
    default: patch

  tag:
    description:
      The tag to update. If not provided, the action will use the latest tag
      found in the repository.
    required: false

outputs:
  next-tag:
    description:
      The next tag to be created based on the provided tag and increment level.

runs:
  using: node20
  main: dist/index.js
