name: Semver Tag Action
description: Analyzes the latest Git tag and calculates the next version by applying a semantic version bump (major, minor, patch, or custom), helping streamline release automation.
author: Acme Software LLC

branding:
  icon: moon
  color: red

inputs:
  milliseconds:
    description: Your input description here
    required: true
    default: '1000'

outputs:
  time:
    description: Your output description here

runs:
  using: node20
  main: dist/index.js
